url: https://yhatt.github.io/marp
title: Marp
subTitle: Markdown Presentation Writer
favicon: https://raw.githubusercontent.com/yhatt/marp/master/images/marp.png
faviconType: image/png
repository_url: https://github.com/yhatt/marp/

build:
  version: 0.0.13
  url:
    windows:
      x86: https://github.com/yhatt/marp/releases/download/v0.0.13/0.0.13-Marp-win32-ia32.zip
      x64: https://github.com/yhatt/marp/releases/download/v0.0.13/0.0.13-Marp-win32-x64.zip
    macosx:
      x64: https://github.com/yhatt/marp/releases/download/v0.0.13/0.0.13-Marp-darwin-x64.dmg
    linux:
      x86: https://github.com/yhatt/marp/releases/download/v0.0.13/0.0.13-Marp-linux-ia32.tar.gz
      x64: https://github.com/yhatt/marp/releases/download/v0.0.13/0.0.13-Marp-linux-x64.tar.gz

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
